// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNwx5mqFWNR_xhRQH4w4DuUYM4Caa76ks',
    appId: '1:258405282975:web:15a1cbc24b6d8767cb1eaa',
    messagingSenderId: '258405282975',
    projectId: 'sflutter-97a66',
    authDomain: 'sflutter-97a66.firebaseapp.com',
    storageBucket: 'sflutter-97a66.appspot.com',
    measurementId: 'G-H290BC3HVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS61vUx9vSmeOUm6_EugcludF2SH9gzOQ',
    appId: '1:258405282975:android:afdb28f1a89f9350cb1eaa',
    messagingSenderId: '258405282975',
    projectId: 'sflutter-97a66',
    storageBucket: 'sflutter-97a66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwbXoGOUtqVB_TwBC7vqYBgdHyngtFe7I',
    appId: '1:258405282975:ios:aa09d541225241f0cb1eaa',
    messagingSenderId: '258405282975',
    projectId: 'sflutter-97a66',
    storageBucket: 'sflutter-97a66.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwbXoGOUtqVB_TwBC7vqYBgdHyngtFe7I',
    appId: '1:258405282975:ios:25e5ce50ec17ec1ccb1eaa',
    messagingSenderId: '258405282975',
    projectId: 'sflutter-97a66',
    storageBucket: 'sflutter-97a66.appspot.com',
    iosBundleId: 'com.example.todolistApp.RunnerTests',
  );
}
